name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  shelf: 1.4.1
  shelf_router: 1.1.4
  shelf_web_socket: 1.0.4
  shelf_cors_headers: 0.1.5
  shelf_plus: 1.7.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
